### ISSUE TITLE
Supporting Docker

### ISSUE THREAD

**Issue by tareksamni** [OfficeDev/O365-Ruby-Microsoft-Graph-Connect#18]
Hi,

Would it be in your interest if I spent sometime to support docker to run your sample? Would you accept my PR and merge it?

Best regards,
/ Tarek

**Comment by jamescro** [comment]
Hi Tarek,
Sorry that we took so long to respond. We're open to PRs (as long as you sign the CLA after you submit the PR), so yes we would be interested.

**Comment by jasonjoh** [comment]
Closing issue for now. Feel free to submit PRs though :)
