### ISSUE TITLE
Why not publish the omniauth-microsoft_v2_auth gem?

### ISSUE THREAD

**Issue by rapind** [OfficeDev/O365-Ruby-Microsoft-Graph-Connect#20]
It's awkward finding the correct omniauth strategy for Microsoft's sign in. Why not publish the gem included here in it's own repo?

Also what's with the the reference to omniauth-office365  here https://github.com/microsoftgraph/ruby-connect-rest-sample/blob/master/omniauth-microsoft_v2_auth/Gemfile#L3

So confused...

**Comment by jamescro** [comment]
Thanks for the feedback. Before I dig into this more deeply, could you take a look at these resources and let us know if they help clarify Omniauth?

https://github.com/omniauth/omniauth/wiki
https://github.com/intridea/omniauth-oauth2

**Comment by rapind** [comment]
I went ahead and built a repo for it here, so we can use the gem w/ bundler: https://github.com/pairshaped/omniauth-microsoft_v2_auth

It's probably better if it lives in the MS repos though.

**Comment by caitlinrussell** [comment]
We have a few steps to go through before we bring this into the Graph repo, but in the meantime, I've cleaned up the code to make the references cleaner.

The omniauth-office365 reference is from an older version of the omniauth strategy.

**Comment by rapind** [comment]
Thanks @cbales
