### ISSUE TITLE
Draft new release

### ISSUE THREAD

**Issue by davegregg** [OfficeDev/O365-Ruby-Microsoft-Graph-Connect#24]
Thanks for merging my PR. I propose a new release be drafted, so anyone downloading the source archive will be getting this latest major update.

**Comment by jamescro** [comment]
I've drafted a new release and tagged the current version to heighten the profile of these updates.

Thanks very much for pushing these updates and for cleaning up the code. May I ask how you found this sample? I'd be curious to gauge interest in Microsoft Graph in the Ruby developer community.

**Comment by davegregg** [comment]
I'm working on a Linux client for OneDrive written in Ruby, so I found this sample on an early exploratory delve through the OneDrive Dev Center.

**Comment by jamescro** [comment]
That's useful to know. Thanks again for the contribution, and for the background.
